### ISSUE TITLE
Getting a message instead of the Media

### ISSUE THREAD

**Issue by feliper** [Sommerregen/grav-plugin-mediaembed#1]
Hi, 
I´m not sure if I´m doing something wrong but this is what I get when I try to use the plugin with this link
  `![UMO](https://soundcloud.com/jagjaguwar/unknown-mortal-orchestra-cant-keep-checking-my-phone)`
  `mediaembed::fa51c2aeb9c6e6276d8a6fc9095d5497::1::M`

Even with your Flickr example I get the same message
`![](https://www.flickr.com/photos/chris_gin/6585842063)
mediaembed::fa51c2aeb9c6e6276d8a6fc9095d5497::2::M
`
I tried to install the plugin manually and through CLI, same message ...
I was in Grav 0.9.23 and update to 0.9.26, and got the same message in both

**Comment by Sommerregen** [comment]
Hm, it looks like something is broken. I will check that this evening.

**Comment by feliper** [comment]
It does, 
without this line everything works fine ... thanks
