### ISSUE TITLE
Support for slides.com (html5 slidedecks)

### ISSUE THREAD

**Issue by paulhibbitts** [Sommerregen/grav-plugin-mediaembed#4]
Great to see this plugin available for Grav!

Might you consider adding direct support for slides.com slidedecks (http://slides.com/)?

Thanks very much,
Paul

**Comment by Sommerregen** [comment]
Hi @paulhibbitts, 

thank you for you kind words! :-D Yes, why not? ;-) I plan it for the next version (maybe releasing it during the upcoming weekend), ok?

It seems that _slides.com_ does not provide an [OEmbed media object](http://oembed.com), but it looks like the structure is as follows

````html
<iframe src="//slides.com/<username>/<project>/embed" width="576" height="420" scrolling="no" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
```

Am I right?

**Comment by paulhibbitts** [comment]
Thanks for considering this request! Yes, that example structure looks right to me.

Here is an actual example from my Grav site:
 
<div class="video-container"><iframe src="http://slid.es/paulhibbitts/cmpt-363-143-course-  overview/embed" height="270" width="340" allowfullscreen="" frameborder="0" scrolling="no">  </iframe></div>

The video-container class is used to help with proportional responsive sizing.

More than  happy to help beta-test anything you like too.

Thanks again!
Paul

**Comment by Sommerregen** [comment]
Dear @paulhibbitts ,

thank you for being so responisve and open for beta-testing! :-) With the latest release today you should embed "**slides.com SlideDecks**" easily within the plugin. I tested the code with your excellent presentation

```
![](http://slides.com/paulhibbitts/enhancing-the-online-experience-for-students-and-instructors-with-a-modern-flat-file-cms/)
```

In the [mediaembed.yaml](https://github.com/Sommerregen/grav-plugin-mediaembed/blob/master/mediaembed.yaml#L222) file you can now configure the size and style of your slides. Whereas the size is maybe unimportant for you, the change of the style is not:

```yaml
params:
  style: "light"        # Footer style: dark, light, hidden
  width: 1920
  height: 1400
```

However play around and have fun!
